# Generated by Django 5.2.7 on 2025-10-29 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
